name: Build and Deploy to Azure Container Apps

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  BACKEND_APP_NAME: backend-container-app
  FRONTEND_APP_NAME: frontend-container-app
  LOCATION: swedencentral

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./backend
          file: backend/Dockerfile
          tags: ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/backend:${{ github.sha }}

      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: frontend/Dockerfile
          tags: ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/frontend:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy backend
        uses: azure/container-apps-deploy-action@v1
        with:
          containerAppName: ${{ env.BACKEND_APP_NAME }}
          containerAppEnvironment: ${{ secrets.CONTAINER_APP_ENVIRONMENT }}
          resourceGroup: ${{ secrets.RESOURCE_GROUP }}
          imageToDeploy: ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/backend:${{ github.sha }}
          location: ${{ env.LOCATION }}
          # environmentVariables: |
          #   ASPNETCORE_ENVIRONMENT=Development

      - name: Deploy frontend
        uses: azure/container-apps-deploy-action@v1
        with:
          containerAppName: ${{ env.FRONTEND_APP_NAME }}
          containerAppEnvironment: ${{ secrets.CONTAINER_APP_ENVIRONMENT }}
          resourceGroup: ${{ secrets.RESOURCE_GROUP }}
          imageToDeploy: ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/frontend:${{ github.sha }}
          location: ${{ env.LOCATION }}
          targetPort: 80